version: '2'
volumes:
  boinc:
services:
  boinc-client:
    build: ./boinc-client
    restart: always
    ports:
      - 31416:31416
    volumes:
      - 'boinc:/usr/app/boinc'
    labels:
      io.balena.features.sysfs: '1'
  boinc-ui:
    build: ./boinc-ui
    restart: always
    privileged: true
    ports:
      - 80:80
