FROM balenalib/%%BALENA_MACHINE_NAME%%

WORKDIR /usr/app

RUN install_packages boinc-client boinctui htop xml-twig-tools 

COPY start*.sh ./

COPY accounts/* ./accounts/

COPY configs/* ./configs/

CMD ["/bin/bash","/usr/app/start.sh"]
